# Generated by Django 4.2.3 on 2023-07-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_description', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=50)),
                ('mentor', models.CharField(max_length=50)),
                ('class_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_description', models.CharField(max_length=200)),
                ('class_price', models.FloatField()),
                ('class_duration', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('paid', models.BooleanField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sati.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sati.student')),
            ],
        ),
    ]
